pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('/'){
                    sh 'mvn package'
                }
            }

        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}